### ISSUE TITLE
Uncaught (in promise) TypeError: Cannot read property 'split' of null

### ISSUE THREAD

**Issue by jcabrera010** [plotly/dash#671] opened 2019-03-28 18:05 UTC
Hi,

I have created an app that displays properly, but the loading time is very slow.
I noticed that there are many errors on the front end that are seen in the console before my app displays any information:

![image](https://user-images.githubusercontent.com/43975493/55181488-fca9ea80-5148-11e9-86b6-8fcf8163d233.png)

![image](https://user-images.githubusercontent.com/43975493/55181545-19deb900-5149-11e9-82a0-4946714bb1d2.png)

version:
dash==0.39.0
dash-auth==1.3.2
dash-core-components==0.44.0
dash-daq==0.1.0
dash-html-components==0.14.0
dash-renderer==0.20.0
dash-table==3.6.0
dash-table-experiments==0.6.0
plotly==3.2.0

**Comment by alexcjohnson** [comment] 2019-04-01 01:10
Thanks for the report @jcabrera010 - It's hard to tell from the above whether it's a bug or a usage problem that we need to report a better error message for. Are you able to share a self-contained version of your app that reproduces these symptoms?

**Comment by jcabrera010** [comment] 2019-04-02 17:47
@alexcjohnson I was able to resolve this.

I was trying to call a function with null ('') parameters. 
Once I added parameters, I no longer saw this error.

Thank you anyway!

**Comment by alexcjohnson** [comment] 2019-04-03 18:24
OK great - so that falls into the category "a usage problem that we need to report a better error message for" - what do you mean by "trying to call a function with null ('') parameters"? Sounds like something we should explicitly trap so future users will be pointed more directly to the source of the problem.

**Comment by jcabrera010** [comment] 2019-04-03 18:43
I had a function (below):

`def indicatortest(title, id_value, id_msg, text, id_timestamp, id_div):
    return html.Div(
        [
            #this is the header for the HX system temperature and oven status
            html.H6(
                title,
                className="tweleve columns indicator_text add", style = {'color':'#000000', 'font-weight':'bold', 'background-color': '#ffffff', 'border':'#000000'}
            ),
            html.P(
                id = id_value,
                className="tweleve columns", style = {'font-size': '25px'}
            ),
            html.P(
                id = id_msg,
                className="tweleve columns", style = {'font-size': '15px', 'font-weight':'bold'}
            ),
            html.P(
                text,
                className="tweleve columns", style = {'font-size': '11px'}
            ),
            html.P(
                id = id_timestamp,
                className="tweleve columns", style = {'font-size': '11px'}
            ),
        ],
        className="six columns indicator", id = id_div, style = {'text-align': 'center'}

    )`

and was calling this function:

`indicator_status(
                        'Oven Status',
                        'ovenstatus_zone4',
                        '',
                        '',
                        '',
                        'zone4_ovenstatus_id'
                    ),`

with null ('') values, the app still displayed properly, but i was seeing this error. When I added parameters the error was no longer there.

**Comment by alexcjohnson** [comment] 2019-04-03 20:32
hmph OK - thanks for the details. I can't reproduce, and the tracebacks you saw don't make much sense to me, `api.js` has no `split` or `recursivelyRender` (the latter doesn't exist at all in the latest version of dash/renderer but in v0.20.0 it was in a different file). I'm going to close the issue but will keep it in mind in case we see something similar in the future.

**Closed by alexcjohnson** 2019-04-03 20:32 UTC
