### ISSUE TITLE
multiple outputs from callback

### ISSUE THREAD

**Issue by bearmountainsolutions** [plotly/dash#417] opened 2018-10-03 17:03 UTC
Please offer a better solution for this.  

I have an interface with a dropdown and a radio group.  Selections then trigger updates to 2 charts, a data table, and a daterange selector (start and end dates).  Writing separate callbacks means repeating the same dependencies.Input clause in 5 places, as well as doing a similar data filter 5 times.  Its not just a performance thing.  It's resulting in repetitive and ultimately hard-to-adapt code.

I know you have a certain design philosophy but this is a real problem.  

Why couldn't the callback clause have been designed to accept a list of depenencies.Output items?

**Comment by chriddyp** [comment] 2018-10-03 17:07
> Why couldn't the callback clause have been designed to accept a list of depenencies.Output items?

It actually has been designed to do this, we just haven't implemented it yet. We're focusing on [other items](https://github.com/orgs/plotly/projects) first that [customers have sponsored](https://plot.ly/products/consulting-and-oem/) before we get to this feature.

This is a duplicate of https://github.com/plotly/dash/issues/149

**Closed by chriddyp** 2018-10-03 17:07 UTC

**Comment by bearmountainsolutions** [comment] 2018-10-03 17:12
Thanks
