### ISSUE TITLE
Button callback called when button wasn't even clicked (also with prevent_initial_call set)

### ISSUE THREAD

**Issue by michael72** [plotly/dash#2620] opened 2023-08-14 06:16 UTC
So, yes, I see that even the documentation of Button + `n_clicks` shows as an example that calls the button callback _initially_  with  `0` or `None` depending on the `n_clicks` parameter being set explicitly to `0` or not set.

See https://dash.plotly.com/dash-html-components/button

But normally _no_ UI library does it like that - a button callback is normally _only_ called when there is an actual click on that button and not initially with `n_clicks` being 0 or None, depending on the value you used in initialization.
Even the `prevent_initial_call` parameter in the callback is just ignored when dealing with buttons, so at least that one should somehow be considered!

There also was an issue #177 on the topic n_clicks being 0 or None ages ago, but it was simply closed with another commit that didn't even address this issue.

So, I would at least expect that the button callback is not called when `prevent_initial_call` is set and the button was _not_ clicked.
I would also expect the `n_clicks` value to be always an integer and never `None`.
Otherwise this makes using a button much more complicated and with surprising results.

**Comment by alexcjohnson** [comment] 2023-08-14 14:32
> Even the `prevent_initial_call` parameter in the callback is just ignored when dealing with buttons

Seems to work, can you show me an example where it doesn't?

```py
from dash import Dash, dcc, html, Input, Output, State, callback

app = Dash(__name__)

app.layout = html.Div([
    html.Div(dcc.Input(id='input-on-submit', type='text')),
    html.Button('Submit', id='submit-val', n_clicks=0),
    html.Div(id='container-button-basic',
             children='Enter a value and press submit')
])

@callback(
    Output('container-button-basic', 'children'),
    Input('submit-val', 'n_clicks'),
    State('input-on-submit', 'value'),
    prevent_initial_call=True
)
def update_output(n_clicks, value):
    return 'The input value was "{}" and the button has been clicked {} times'.format(
        value,
        n_clicks
    )

if __name__ == '__main__':
    app.run(debug=True)
```
<img width="228" alt="Screenshot 2023-08-14 at 10 25 13" src="https://github.com/plotly/dash/assets/2678795/1c1aa4d3-219b-4a6f-9db1-a647686cbc99">

You're right though, we should add `prevent_initial_call=True` to that example.

> There also was an issue https://github.com/plotly/dash/issues/177 on the topic n_clicks being 0 or None ages ago, but it was simply closed with another commit that didn't even address this issue.

#177 was closed not by changing the behavior but based on having improved the documentation of the existing behavior. There's a commit that appears to reference the issue but it's an artifact of having merged several repos together

**Comment by kyoshizzz** [comment] 2023-10-03 04:30
i found the solution :
remove n_clicks = 0 when you declare the html.Button at layout and it will fixed it
its because you define it as 0 then it will triggered the callback

**Comment by gvwilson** [comment] 2024-07-25 13:53
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are most important to our community. If this issue is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. (Please note that we will give priority to reports that include a short reproducible example.) If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson

**Closed by gvwilson** 2024-07-25 13:53 UTC
