### ISSUE TITLE
Dash Application fails to load with IE Compatibility View

### ISSUE THREAD

**Issue by drRussClay** [plotly/dash#339] opened 2018-08-16 20:25 UTC
I am hosting a Dash application internal to my organization and one of our users reported a page load error on IE 11.  Investigation revealed that the user had our internal website domain listed in IE's Compatibility View settings.  I confirmed on my own machine that adding the domain to compatibility view reproduced the error and removing the domain from compatibility view immediately allowed the page to load.

Is there a known workaround in Dash so that pages will load even if the domain is in compatibility view?

Screenshot of the page load error attached

![image](https://user-images.githubusercontent.com/17880365/44232871-5f2d1800-a170-11e8-8ef8-e23914101981.png)

**Comment by chriddyp** [comment] 2018-08-16 20:34
Thanks for reporting @drRussClay ! This was last discussed in https://github.com/plotly/dash/pull/275, and we decided to add the tag. In code, it's here: https://github.com/plotly/dash/blob/7361db52690810891c5f68501eda1d71043cb777/dash/dash.py#L378-L394

Could you confirm that you are using the latest version of Dash that has these changes? Or, are these changes causing the new issues?

**Comment by drRussClay** [comment] 2018-08-16 20:53
I'm using version 0.21.0, and since this fix is pretty new, I'm guessing I don't have it included. I will update and test to see if it fixes the problem. Thanks!

**Comment by chriddyp** [comment] 2018-08-16 20:55
Thanks! You can see the list of changes in the changelog here: https://github.com/plotly/dash/blob/master/CHANGELOG.md. It looks like it's part of 0.23.1

**Comment by drRussClay** [comment] 2018-08-21 15:30
I made the update but it doesn't solve the problem.  If I add the website domain to compatibility view settings, my application will not load.  I'm on Dash version 0.25.1.  I also tried updating dash core components, dash html components, and dash renderer to the most current versions but it did not fix the issue.  Any suggestions?  I am serving the application via IIS; could that have something to do with it?

**Comment by ShahnurIslam** [comment] 2019-02-15 13:25
I'm having the same issue, so a fix would be great!

**Comment by pope1ni** [comment] 2019-02-27 09:53
@drRussClay - there was a [bug](https://github.com/plotly/dash/pull/316#pullrequestreview-160626231) in the meta tag definition that was fixed in [v0.28.3](https://github.com/plotly/dash/blob/master/CHANGELOG.md#0283---2018-10-17)

**Comment by gvwilson** [comment] 2024-07-17 13:10
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are most important to our community. If this issue is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. (Please note that we will give priority to reports that include a short reproducible example.) If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson

**Closed by gvwilson** 2024-07-17 13:10 UTC
