### ISSUE TITLE
[BUG] AttributeError: module 'dash' has no attribute 'Dash'

### ISSUE THREAD

**Issue by raybg** [plotly/dash#1419] opened 2020-09-29 18:12 UTC
When im trying to run my existing .py file which was working a while ago , has started giving me the Attribute error. 

dash                 1.16.1
dash-core-components 1.12.1
dash-html-components 1.1.1
dash-renderer        1.8.1
dash-table           4.10.1

 - OS: [e.g. iOS] - Win 10

**Describe the bug**
Attribute Error is coming all of a sudden, previously tried to Conda Activate and it got resolved, i dont know how its related, but it was resolved. I tried now also but error still persisted.
If anyone get explain me in a non-technical manner to resolve this issue once for all.
- Dash (Latest Version)
- Tried running with Jupyter, CMD, all giving the same attribute error only.
- Tried with the following imports too 
import pandas as pd
from .dash import Dash, no_update  # noqa: F401
from . import dependencies  # noqa: F401
from . import development  # noqa: F401
from . import exceptions  # noqa: F401
from . import resources  # noqa: F401
from .version import __version__  # noqa: F401
from ._callback_context import callback_context  # noqa: F401
import dash_html_components as html
import dash_core_components as dcc
from dash.dependencies import Input, Output
import plotly.express as px
import plotly.graph_objects as go 
from plotly.subplots import make_subplots
import flask

ERROR MSG :
~\AppData\Local\Continuum\anaconda3\lib\site-packages\future\standard_library\__init__.py in __enter__(self)
    779             #             pass
    780             try:
--> 781                 module = __import__(m, level=0)
    782             except ImportError:
    783                 # There's a problem importing the system module. E.g. the

~\Desktop\Cogencis Office\Cogencis Project\financialreport\test.py in <module>
      1 import pandas as pd
      2 import dash
----> 3 from jupyter_dash import JupyterDash
      4 import dash_html_components as html
      5 import dash_core_components as dcc

~\AppData\Local\Continuum\anaconda3\lib\site-packages\jupyter_dash\__init__.py in <module>
      1 import jupyter_dash.comms
----> 2 from .jupyter_app import JupyterDash
      3 from .version import __version__
      4 
      5 def _jupyter_nbextension_paths():

~\AppData\Local\Continuum\anaconda3\lib\site-packages\jupyter_dash\jupyter_app.py in <module>
     24 
     25 
---> 26 class JupyterDash(dash.Dash):
     27     """A Dash subclass for developing Dash apps interactively in Jupyter.
     28 

AttributeError: module 'dash' has no attribute 'Dash'

**Comment by Duaran** [comment] 2020-09-29 21:59
Try to rename the file by something else than test.py. I had the same error and it went well just by rename the file, maybe it will work for you too.

**Comment by raybg** [comment] 2020-09-30 05:46
Yaa that worked great !!... i had one file with that name .. If there are any exceptions except for dash.py and test.py, which we need to avoid, please let me know.

Thx and Rgrds

**Comment by alexcjohnson** [comment] 2020-09-30 15:47
Thanks @Duaran ! For reference there's also `org.py` - duplicate of #1143

**Closed by alexcjohnson** 2020-09-30 15:47 UTC

**Comment by saeed-sufi** [comment] 2021-02-15 09:15
I had two files in a directory, one off them was named 'test.py'. While trying to run the other .py file, I got the same error. Deleting (or renaming) 'test.py' file from the directory, solved the issue.

**Comment by balaji36918** [comment] 2022-06-09 04:27
Hey, thanks for the message. I am facing the same problem but I dont have any file with the name test.py. Please suggest me a measure.

version:
dash  = 0.36.0
dash-core-components = 1.17.1
dash-html-components = 1.1.4

Thanks in advance

**Comment by amanwissen** [comment] 2023-04-27 09:29
same issue
