### ISSUE TITLE
[BUG] Background callbacks - Error with Pattern Matching in Running option

### ISSUE THREAD

**Issue by slyin87** [plotly/dash#2499] opened 2023-04-07 00:34 UTC
**Describe your context**
I use background callback with Celery + Redis. In the example there is a running option to put in the components. The thing is I am using pattern matching. If I remove the running option, there is no problem.

This is my app.py:
![image](https://user-images.githubusercontent.com/90740896/230517143-231ce2be-a20e-441d-8abb-84c13aff95df.png)

This is my callback:
![image](https://user-images.githubusercontent.com/90740896/230517786-9c833c9a-e409-4a6d-8b9c-95bfa0dab374.png)

```
dash                      2.9.0
dash-bootstrap-components 1.4.1
dash-core-components      2.0.0
dash-html-components      2.0.0
dash-mantine-components   0.12.0
dash-table                5.0.0
```

**Describe the bug**

the running option using background callback does not work. Moreover, Why do I see it is a long callback instead of background callback?
Error:
```
File "/usr/local/lib/python3.10/site-packages/dash/_callback.py", line 167, in callback
    validate_long_inputs(x[0] for x in long_spec["running"])
  File "/usr/local/lib/python3.10/site-packages/dash/_callback.py", line 209, in validate_long_inputs
    raise WildcardInLongCallback(
dash.exceptions.WildcardInLongCallback: long callbacks does not support dependencies with
pattern-matching ids
    Received: <Output `{"index":["MATCH"],"type":"main_apm_generate_boxplot_button"}.disabled`>
```

**Comment by Ciaran-YouSeq** [comment] 2023-04-12 09:37
i'm having the same issue with `DiskcacheManager` in `dash 2.9.2`. I'm a bit confused by this error as the docs (https://dash.plotly.com/background-callbacks) say pattern matching is supported for background callbacks, but in the `validate_long_inputs` method in `_callback.py` there is no mechanism that allows pattern matching - it will always raise `WildcardInLongCallback`

**Comment by T4rk1n** [comment] 2023-04-12 17:31
Pattern matching is supported for inputs and outputs but it was not implemented for progress, running and cancel.
https://github.com/plotly/dash/issues/2111

**Comment by nickmelnikov82** [comment] 2023-06-03 07:36
Hi, your situation is interesting and I found 3 similar errors that might be useful for you:

1. [Possible bug with callbacks](https://github.com/plotly/dash/issues/1837)
2. [Callback executes but return value has no effect](https://github.com/plotly/dash/issues/1075)
3. [Pattern-matching callbacks with empty or partly-empty Output](https://github.com/plotly/dash/issues/1216)

**Comment by T4rk1n** [comment] 2024-03-28 20:27
Duplicate of #2111

**Closed by T4rk1n** 2024-03-28 20:27 UTC
