### ISSUE TITLE
animation pause when browser focus lost

### ISSUE THREAD

**Issue by xialu4820723** [plotly/dash#213] opened 2018-03-02 19:31 UTC
I am writing a log processing and presenting project by dash. Which will fetch the log count and draw it as a scatter picture. data updated by every 5 seconds. looks like this:
```python
interval = dcc.Interval(
    id='interval',
    interval=5 * 1000,
    n_intervals=0
)
graph = dcc.Graph(
    id='graph',
    animate=True,
)
app.layout = html.Div(children=[
    graph,
    interval,
])
@app.callback(Output('graph', 'figure'),
              [Input('interval', 'n_intervals')])
def refresh_figure_data(n):
    trace = go.Scatter(
        x=range(10),
        y=get_log_count_from_db(),
        mode='lines',
        name='scatter'
    )
    return {
        'data': [trace]
    }
```
The animation is beautiful, you can see the line tail move slightly for every 5 seconds, but when I switch to other tab of browser, working for a while and switch back, bad thing happen.
**It seems that the animation will stop when the dash page lose browser focus,and redraw all the animations stored during the departure one by one slowly as soon as it get focus again.**

So I have to refresh the page to get latest picture.

I have check [this](https://plot.ly/javascript/animations/#frame-groups-and-animation-modes), no solution was found. Is there a way to tell dash continue drawing during window.onblur?

**Comment by chriddyp** [comment] 2018-06-08 01:05
This is a duplicate of https://github.com/plotly/dash-core-components/issues/208

**Closed by chriddyp** 2018-06-08 01:05 UTC

**Comment by SumeetJindal** [comment] 2023-04-21 12:13
I'm not sure if the issue is fixed but I'm having the same problem. I have live chart to display the current price but when the tab is inactive, the chart stops updating. The callbacks are working fine, as I am printing the price on each callback, but unfortunately the browser applies/replays each and every update until it catches up.
