### ISSUE TITLE
Boolean props don't persist when False

### ISSUE THREAD

**Issue by tcbegley** [plotly/dash#1034] opened 2019-12-01 23:37 UTC
Hello,

I'm trying to add support for the persistence feature (which is awesome btw) to dash-bootstrap-components. I'm having some trouble in the case where the prop to be persisted is boolean. Specifically it seems that if the user changes the prop value to `False` then the change is not stored and so the new value is not persisted when the page is refreshed.

I tried playing around with persistence transforms to see if I could get it to work, but it seems those aren't even triggered when the prop in question is `False`.

Is there a workaround for this or something I should be doing differently? I didn't get a chance to check properly how the persistence is working so I possibly just misunderstood something.

In case it's helpful to diagnose, [here's the diff](https://github.com/facultyai/dash-bootstrap-components/compare/master...persistence) on what I added to support persistence. `Alert`, `Checkbox`, `Collapse`, `Modal` and `RadioButton` all have boolean props that aren't persisting properly when I test it out.

**Comment by alexcjohnson** [comment] 2019-12-02 01:48
Thanks @tcbegley - Implied there is that the *default* value is `True` and you're trying to store `False`. I haven't confirmed but it looks likely coming from this line:

https://github.com/plotly/dash/blob/bed099ad2d5f6c3ab0aa5c5674524005f9d0d3a9/dash-renderer/src/persistence.js#L291

Which should presumably change to something like:
```js
const getVal = prop => (props[prop] !== undefined ? props : (element.defaultProps || {}))[prop]; 
```
(The PR might just be one line but it'll also need a test with a default-true prop)

**Comment by tcbegley** [comment] 2019-12-02 07:06
Thanks for the speedy response @alexcjohnson 

> Implied there is that the default value is `True` and you're trying to store `False`.

Yes that’s right. With hindsight my original post is not terribly clear, sorry.

**Comment by byronz** [comment] 2019-12-17 03:54
I have two use cases could be covered with integration tests:

1. `dcc.Dropdown` select an option and clear it with a mouse click on the `x` 
2. `dcc.Input` just clear the value with key press

@alexcjohnson both are very typical use cases as user input. the app has about 10 dropdowns for different dimensions, and the fact the persistence cannot store these Empty or None values is very annoying as it always shows up with a full list of VALID strings (some of them were just selected once and cannot be intentionally cleaned up)

**Comment by eddy-geek** [comment] 2020-04-07 21:14
Fixed by  #1142

**Closed** 2020-05-06 07:44 UTC
Labels: dash-type-bug

**Comment by MM-Lehmann** [comment] 2020-06-24 09:51
I would like to reopen this one:
When clearing a dbc.Input component, the last value is persisted rather than "None"

**Comment by alexcjohnson** [comment] 2020-06-24 15:59
@MM-Lehmann if you can reproduce the effect with a core component eg `dcc.Input` we can reopen here; otherwise it may be specific to the `dbc` implementation in which case it would be better to open an issue at https://github.com/facultyai/dash-bootstrap-components/issues

**Comment by MM-Lehmann** [comment] 2020-06-24 18:01
Good advice, I should've checked that before posting :(
Actually, it does work with `dcc.Input`. I guess I will post an issue on their project then.
