### ISSUE TITLE
min.js.map MIME type not executable

### ISSUE THREAD

**Issue by boludo00** [plotly/dash#488] opened 2018-12-11 23:49 UTC
Hello all,
I am working on a serverless deployment of a Dash project and I am getting some console errors:

`Refused to execute script from 'https://unpkg.com/dash-core-components@0.40.3/dash_core_components/dash_core_components.min.js.map' because its MIME type ('application/json') is not executable, and strict MIME type checking is enabled.`

`Refused to execute script from 'https://unpkg.com/dash-renderer@0.16.0/dash_renderer/dash_renderer.min.js.map' because its MIME type ('application/json') is not executable, and strict MIME type checking is enabled.`

Has anyone ran into this before? I tried searching for past related issues but did not have much luck getting around this. I'm pretty new with Dash so I don't know how to interpret this.

**Comment by T4rk1n** [comment] 2018-12-12 00:17
Update dash to latest with `pip install dash --upgrade`

**Comment by edwindt** [comment] 2018-12-20 17:06
Hello, I'm having exactly the same issue.  Everything is updated in dash, the dashboard works but it takes some time (~15 sec) to render the components, even for very simple dashboards. I guess it may be associated to the problem to execute the dash_core component....Any workaround will be greatly appreciated

**Comment by MarcSkovMadsen** [comment] 2018-12-21 10:11
I'm also using Dash seeing the issue in my Chrome console

"Refused to execute script from 'https://unpkg.com/dash-core-components@0.41.0/dash_core_components/dash_core_components.min.js.map' because its MIME type ('application/json') is not executable, and strict MIME type checking is enabled.

Refused to execute script from 'https://unpkg.com/dash-renderer@0.16.1/dash_renderer/dash_renderer.min.js.map' because its MIME type ('application/json') is not executable, and strict MIME type checking is enabled."

I'm on dash version 0.35.0, plotly version 3.3.0 and django_plotly_dash version 0.9.4

**Comment by OmenApps** [comment] 2018-12-24 07:00
I get both of the following when using

- plotly 3.4.2
- dash 0.35.0
- django 2.1.4
- django_plotly_dash 0.9.4
- python 3.7.1

> Refused to execute script from 'https://unpkg.com/dash-core-components@0.41.0/dash_core_components/dash_core_components.min.js.map' because its MIME type ('application/json') is not executable, and strict MIME type checking is enabled.
> 127.0.0.1/:1 
> 
> Refused to execute script from 'https://unpkg.com/dash-renderer@0.16.1/dash_renderer/dash_renderer.min.js.map' because its MIME type ('application/json') is not executable, and strict MIME type checking is enabled.

**Comment by nicolaskruchten** [comment] 2018-12-24 13:49
Is this preventing your app from executing or is it just a warning in the console?

**Comment by T4rk1n** [comment] 2018-12-24 14:49
> django_plotly_dash 0.9.4

They handle the bundles differently and need to patch it to not auto serve the dist items marked as `dynamic`.

**Comment by OmenApps** [comment] 2018-12-26 21:04
> Is this preventing your app from executing or is it just a warning in the console?

Just warning in console, and app doesn't function properly. It displays the components, but no actual data is displayed.

**Comment by T4rk1n** [comment] 2018-12-26 22:16
@boludo00 Can you confirm that you are also using django_plotly_dash ?

**Comment by delsim** [comment] 2018-12-27 05:09
@T4rk1n I have to admit that I don't completely follow your remark about not auto serving certain items, as the django_plotly_dash code just relies on dash functionality to generate the list of scripts to be included, but after some experimentation I have found that a patch to the function ``Dash._collect_and_register_resources`` in dash.py removes the warning message.

Specifically, I'm adding a test for a resource to not be dynamic when an ``external_url`` is specified at about line 400 in dash/dash.py:
```python
           elif 'external_url' in resource:
                if not is_dynamic_resource:   #<<< ADDING THIS TEST
                    if isinstance(resource['external_url'], str):
                        srcs.append(resource['external_url'])
                    else:
                        for url in resource['external_url']:
                            srcs.append(url)
            elif 'absolute_path' in resource: 
```

It is not clear to me if this is an oversight in the dash code, or if for some reason the resources in question (which come from the dash_renderer package) should have a ``relative_package_path`` property, or if the django_plotly_dash code is doing something inappropriate.

**Comment by T4rk1n** [comment] 2018-12-27 21:00
@delsim 

> It is not clear to me if this is an oversight in the dash code,

I thought `django_plotly_dash` had custom index rendering, sorry. From that snippet it does look like `dynamic` for `external url` is not considered, thanks for the investigation.

**Comment by T4rk1n** [comment] 2019-01-04 19:22
Dash 0.35.1 fixes the `.map` console issue, I don't think the performance issue is related.

@edwindt Please open a new issue with a reproducible example if you still encounter the long loading times after upgrading dash to 0.35.1.

**Closed by T4rk1n** 2019-01-04 19:22 UTC

**Comment by KrishnaChaitanya-Gopaluni** [comment] 2022-02-24 00:01
> Update dash to latest with `pip install dash --upgrade`
Thanks it worked for me. Along with dash upgrade, I had to upgrade dash-auth, dash-core-components, dash-html-componets, and dash-render for my dash application. May be, this is not relevant for others.
