### ISSUE TITLE
Running argument in a callback breaks when provided with a dictionary as an component_id instead of a string

### ISSUE THREAD

**Issue by MohammadSakhnini** [plotly/dash#2815] opened 2024-03-26 12:02 UTC
Dash version - 2.6.1

This breaks:
running=[(Output({"type": "dwn_panel_download_btn", "page": "dp_wiki"}, "disabled"), True, False)]

This works:
running=[(Output("dwn_panel_download_btn", "disabled"), True, False)]

**Screenshots**

![image](https://github.com/plotly/dash/assets/49996190/7b2f2a3d-98b1-46e8-9063-387e06abc627)

**Comment by T4rk1n** [comment] 2024-03-28 20:21
Duplicate of #2111

**Closed by T4rk1n** 2024-03-28 20:21 UTC
Labels: bug, sev-2
