### ISSUE TITLE
[BUG] Dash Callback background with pattern-matching running outputs doesn't cascade

### ISSUE THREAD

**Issue by Mereep** [plotly/dash#2340] opened 2022-11-29 12:10 UTC
**Describe your context**

-  replace the result of `pip list | grep dash` below
```
dash                      2.7.0
dash-bootstrap-components 1.2.1
dash-core-components      2.0.0
dash-html-components      2.0.0
dash-mantine-components   0.10.2
dash-table                5.0.0
```

**Describe the bug**

I have the following concrete `app.callback` definition for filter buttons:
```python
@app.callback(Output(LAYOUT_IDS.FILTER_STORAGE.value, 'data'),
              Input({'type': LAYOUT_IDS.FILTER_APPLY.value, 'index': ALL},
                    'n_clicks'),
              Input(
                  {'type': LAYOUT_IDS.FILTER_DELETE.value, 'index': ALL},
                  'n_clicks'
              ),
              State(
                  {'type': LAYOUT_IDS.FILTER_INPUT.value, 'index': ALL},
                  'value'
              ),
              running=[
                  (Output(LAYOUT_IDS.FILTER_RESULTS_WRAPPER.value, 'className'), 'loading', 'not-loading'),
                  # (Output({'type': LAYOUT_IDS.FILTER_APPLY.value, 'index': 1}, 'disabled'), True, False),
                  # (Output({'type': LAYOUT_IDS.FILTER_APPLY.value, 'index': 2}, 'disabled'), True, False),
              ],
              prevent_initial_call=True,
              background=True,
              manager=get_disk_cache_manager()
              )
```

which is working fine, unless any of the pattern matching `Outputs` in `running` are enabled. The cascading trigger to the connected callback (`LAYOUT_IDS.FILTER_STORAGE.value, 'data'`) will  not be triggered (again: **WILL BE** triggered correctly w/o pattern `Output`).  There is no error thrown and the page is Updating forever.

**Expected behavior**
Output should cascade to next callback, even if there are pattern matching Outputs in `running`.

**Comment by T4rk1n** [comment] 2024-03-28 20:22
Duplicate of #2111

**Closed by T4rk1n** 2024-03-28 20:22 UTC
