### ISSUE TITLE
Add Callbacks visualization visual test

### ISSUE THREAD

**Issue by Marc-Andre-Rivet** [plotly/dash#1175] opened 2020-04-01 16:58 UTC
Basic sanity test for the callbacks visualization.
Would have prevented regression fixed in https://github.com/plotly/dash/pull/1103 and https://github.com/plotly/dash/pull/1174 (cherry-picked from #1103)

**Comment by alexcjohnson** [comment] 2020-04-01 19:00
duplicate of #1166

**Closed by alexcjohnson** 2020-04-01 19:00 UTC
Labels: dash-attribute-maintainability, dash-type-enhancement, size: 0.5
