### ISSUE TITLE
[BUG] Integrated JupyterDash fails to display running app.

### ISSUE THREAD

**Issue by mmwinther** [plotly/dash#2629] opened 2023-08-22 10:37 UTC
**Describe your context**
```
dash                      2.12.1
dash-bootstrap-components 1.4.2
dash-core-components      2.0.0
dash-html-components      2.0.0
dash-table                5.0.0
jupyter-dash              0.4.2
```
JupyterLab 3.6.1

**Describe the bug**

Using the JupyterDash integrated into the dash package does not:

- Infer the Jupyter proxy
- Display the running app

This is observed running bot `inline` and `jupyterlab` modes.

[Notebook with minimal reproduction (gist)](https://gist.github.com/mmwinther/f7ad64e94926a7aaa85ee4f784697053)

**Expected behavior**

I expect using JupyterDash from the `dash` package to match the functionality of that from the `jupyter_dash` package and that described on https://dash.plotly.com/dash-in-jupyter.

Fundamentally, I expect to be able to display the running app.

**Screenshots**

Displays Hello World 👇 
![Screen Shot 2023-08-22 at 12 32 13](https://github.com/plotly/dash/assets/42948872/6f8aef38-c283-4bd1-91f4-42cf60165363)

Doesn't display Hello World 👇 
![Screen Shot 2023-08-22 at 12 32 36](https://github.com/plotly/dash/assets/42948872/7185c57d-512f-47ff-bda4-ac2774cf8780)

Running `jupyter_dash.infer_jupyter_proxy_config()` 👇 

![Screen Shot 2023-08-22 at 12 44 08](https://github.com/plotly/dash/assets/42948872/0c4e6848-04df-4f49-8258-aae4419b0947)

**Comment by T4rk1n** [comment] 2023-08-22 13:14
JupyterDash is deprecated and should not be used with the latest dash as that causes double render as seen in your first screenshot (first fail/second got the render).

**Comment by mmwinther** [comment] 2023-08-22 17:09
Hi @T4rk1n thanks for the comment. I ran them in the same environment for convenience of producing a minimal reproduction of the bug. 

I have not been able to display a Dash app using the newer integrated version (v2.11+) when there is only the `dash` package installed either.

We've never had an issue using the deprecated `jupyter_dash` package and as you can see, it still works. 

I'm not sure whether there's something missing from the documentation or if it is just a bug, we're running in a Jupyterhub on Kubernetes environment if that helps.

**Comment by davy39** [comment] 2023-08-24 10:38
Is Jupyterlab is running locally ans accessed via `127.0.0.1` ?

If it's proxied with a domain name, you have to `pip install jupyter-server-proxy`,  and

```python   
# Some code here
app = Dash(__name__,  requests_pathname_prefix="/proxy/7001")
# some code here
app.run(mode="tab",jupyter_server_url=<your_domain_name>, port=7001)
```
Your app will then be served at : `<your_domain_name>/proxy/7001`

**Comment by mmwinther** [comment] 2023-08-25 13:21
Thanks for the help @davy39 I've got it working now. It's a shame that it requires so much more config than it did with the deprected `jupyter_dash` package.

Here's a code example for anyone else attempting it:
```
import os
from dash import Dash, html
port = 7002
service_prefix = os.getenv('JUPYTERHUB_SERVICE_PREFIX', '/')
domain = os.getenv('JUPYTERHUB_HTTP_REFERER', None)
app = Dash(__name__, requests_pathname_prefix=f"{service_prefix}proxy/{port}/")
app.layout = html.Div([html.H1("Hello world")])
app.run(jupyter_mode="inline", jupyter_server_url=domain, port=port)
```
`Dash app running on https://<domain>/user/<username>/proxy/7002/`

Note that `requests_pathname_prefix` must *both* start and end with a `/`

**Comment by alexcjohnson** [comment] 2023-08-25 19:14
@mmwinther the intent was not to drop any functionality when we merged `jupyter-dash` into `dash`, so either there's some sort of a bug here - a case we didn't properly port over - or we just haven't documented the shift properly. Can you say more about your setup? I gather from the `os.getenv('JUPYTERHUB_...` calls that you're using Jupyter Hub, I don't see those env vars in our code but if they're standard perhaps we could look for them directly and do exactly what you have here internally when we find them. @T4rk1n thoughts?

**Comment by MagnusCaspersen184** [comment] 2023-11-03 10:19
We are facing the same issue as @mmwinther mentioned. We run a JupyterHub service, with Kubernetes. 
Previously we would just call: 
`from jupyter_dash.comms import _send_jupyter_config_comm_request
_send_jupyter_config_comm_request()`

And jupyter-dash would automatically fix correct URLs (using the proxy setup). But now that call does nothing and we face the same error. 
If we try using 
`JupyterDash.infer_jupyter_proxy_config()`

We also see the same error as @mmwinther:

OSError: Unable to communicate with the jupyter_dash notebook or JupyterLab 
extension required to infer Jupyter configuration.

**Comment by cbrochtrup** [comment] 2023-11-21 14:08
I'm running into the same issue described but [this fix](https://github.com/plotly/dash/issues/2629#issuecomment-1693354750) doesn't work for my JupyterHub environment.

**Comment by driehle** [comment] 2023-11-21 16:37
I was running into the same issue as well, but for me I can confirm that [mmwinter's solution](https://github.com/plotly/dash/issues/2629#issuecomment-1693354750) works pretty much out of the box. However, on my JupyterHub the environment variable `JUPYTERHUB_HTTP_REFERER` was not present, so I simply set `domain = "https://www.example.org/"` and then it worked.

Hence, I suggest starting with `jupyter_mode="external"`  to manually look at the URL generated. In a JupyterHub environment, the URL must look like `https://www.example.org/user/username/proxy/1234/`. Obviously, with your domain name, your username and whatever port you have chosen.

My environment is a Docker-based JupyterHub installation with JupyterLab. The installed package versions are as follows:

```bash
$ pip list | grep -E "jupyter|dash|plotly"
dash                          2.14.1
dash-core-components          2.0.0
dash-html-components          2.0.0
dash-table                    5.0.0
jupyter_client                8.6.0
jupyter_core                  5.5.0
jupyter-events                0.9.0
jupyter-lsp                   2.2.0
jupyter_server                2.10.1
jupyter_server_proxy          4.1.0
jupyter_server_terminals      0.4.4
jupyter-telemetry             0.1.0
jupyterhub                    4.0.2
jupyterlab                    4.0.9
jupyterlab_geojson            3.4.0
jupyterlab-pygments           0.2.2
jupyterlab_server             2.25.2
jupyterlab-widgets            3.0.9
plotly                        5.18.0
```

Without manually setting `requests_pathname_prefix`, `jupyter_server_url` and `port` I had the same error message as mentioned above:

```
OSError: Unable to communicate with the jupyter_dash notebook or JupyterLab
extension required to infer Jupyter configuration.
```

I recognized, however, that the JupyterLab Extension Manager shows the extension jupyterlab-plotly and plotly-dash-jupyterlab as faulty, as indicated by the red bar on the left side. I have to admit, at first I was unsure what the red bar means, but looking at the HTML code these elements have a class `jp-extensionmanager-entry-error` assigned, so I assume that this is an error.

![grafik](https://github.com/plotly/dash/assets/1586788/3dd70700-8424-4b99-9b37-ddf8b5666f8c)

Checking the output of `jupyter labextension list` I can see that indeed there seems to be an issue with these extensions. However, I was unsuccessfull in finding any log files or a reason why they are failing.

```
$ jupyter labextension list
JupyterLab v4.0.9
/opt/conda/share/jupyter/labextensions
        jupyterlab_pygments v0.2.2 enabled  X (python, jupyterlab_pygments)
        jupyterlab-plotly v5.18.0 enabled  X
        @jupyter-notebook/lab-extension v7.0.6 enabled OK
        @jupyterhub/jupyter-server-proxy v4.1.0 enabled OK
        @jupyter-widgets/jupyterlab-manager v5.0.9 enabled OK (python, jupyterlab_widgets)
        @jupyterlab/geojson-extension v3.4.0 enabled OK (python, jupyterlab-geojson)


   The following extensions are outdated:
        jupyterlab_pygments
        jupyterlab-plotly
        
   Consider checking if an update is available for these packages.

Other labextensions (built into JupyterLab)
   app dir: /opt/conda/share/jupyter/lab
        @plotly/dash-jupyterlab v0.4.3 enabled  X

   The following extensions are outdated:
        @plotly/dash-jupyterlab
        
   Consider checking if an update is available for these packages.
```

Could it be that `dash` is not compatible with JupyterLab 4, but with JupyterLab 3 only? I have not tested it with JupyterLab 3 though. However, given that the extensions are erroneous, I am no longer surprised that the auto-configuration failes. Setting the parameters manually does the trick though.

**Comment by Coding-with-Adam** [comment] 2023-11-22 17:15
@driehle Thank you for sharing the fix. For those that are just starting with JupyterDash, as of [Dash 2.11.0](https://community.plotly.com/t/dash-2-11-0-released-dash-in-jupyter-locked-flask-versions-and-dcc-graph-updates/76494#dash-in-jupyter-environments-2), you can run Dash apps in classic Jupyter Notebooks and in JupyterLab without the need to update the code or use the additional JupyterDash library.

Dash should work flawlessly with JupyterLab 3.

**Comment by Coding-with-Adam** [comment] 2023-11-22 17:16
Closing the issue for now, since a fix has been found. But if anyone would like to continue discussing, we can re-open.

**Closed by Coding-with-Adam** 2023-11-22 17:16 UTC
