### ISSUE TITLE
[BUG] v1.3.0 breaks max_date_allowed parameter of dcc.DatePickerSingle

### ISSUE THREAD

**Issue by akbo** [plotly/dash#933] opened 2019-09-19 14:16 UTC
**Describe your context**

```
dash                 1.3.0    
dash-core-components 1.2.0    
dash-html-components 1.0.1    
dash-renderer        1.1.0    
dash-table           4.3.0
```

    - OS: macOS 10.14.6
    - Browser Chrome
    - Version 76.0.3809.132

**Describe the bug**

This bug doesn't show up in dash==1.2.0, only in dash==1.3.0. Running the first example code snippet for DatePickerSingle [(link)](https://dash.plot.ly/dash-core-components/datepickersingle), when clicking on the date picker to select a date, I get the following error popup (see screenshot below):
```
Cannot read property 'has' of undefined
```

Code snippet run:
```
from datetime import datetime as dt
import dash
from dash.dependencies import Input, Output
import dash_html_components as html
import dash_core_components as dcc

external_stylesheets = ['https://codepen.io/chriddyp/pen/bWLwgP.css']

app = dash.Dash(__name__, external_stylesheets=external_stylesheets)
app.layout = html.Div([
    dcc.DatePickerSingle(
        id='my-date-picker-single',
        min_date_allowed=dt(1995, 8, 5),
        max_date_allowed=dt(2017, 9, 19),
        initial_visible_month=dt(2017, 8, 5),
        date=str(dt(2017, 8, 25, 23, 59, 59))
    ),
    html.Div(id='output-container-date-picker-single')
])


@app.callback(
    Output('output-container-date-picker-single', 'children'),
    [Input('my-date-picker-single', 'date')])
def update_output(date):
    string_prefix = 'You have selected: '
    if date is not None:
        date = dt.strptime(date.split(' ')[0], '%Y-%m-%d')
        date_string = date.strftime('%B %d, %Y')
        return string_prefix + date_string


if __name__ == '__main__':
    app.run_server(debug=True)
```

Using dash==1.3.0, the error does not show up when removing the max_date_allowed parameter. The error is only present, if the max_date_allowed parameter is present.

**Expected behavior**

The date picker should work as intended, not throw an error when trying to pick a date.

**Screenshots**

<img width="626" alt="Screen Shot 2019-09-19 at 16 01 03" src="https://user-images.githubusercontent.com/1926271/65251828-4cfe7580-daf8-11e9-8bc6-bae5339920f3.png">

**Comment by Marc-Andre-Rivet** [comment] 2019-09-19 14:23
@akbo Thanks for the feedback.

This is a duplicate of https://github.com/plotly/dash-core-components/issues/652.
The regression fix has been released https://community.plot.ly/t/dash-v1-3-1-released/28940

Closing as fixed.

**Closed by Marc-Andre-Rivet** 2019-09-19 14:23 UTC
Labels: Type: Bug
