### ISSUE TITLE
Component property 'figure' will not update hover-text for go.Heatmap object

### ISSUE THREAD

**Issue by SterlingButters** [plotly/dash#224] opened 2018-03-18 06:32 UTC
I have a very long code with many dependencies and I would happy to upload it but I feel it might be easier to see if the problem can be reproduced on a simpler scenario. The snippet where the problem is, is here:

```
# Fill Region
@app.callback(
    Output('planes-graph', 'figure'),
    [Input('planes-list', 'value'),
     Input('fill-region-button', 'n_clicks')],
    [State('material-dropdown', 'value'),
     State('click-register', 'children')]
)
def fill_region(planes, n_clicks, selected_material, click_register):
    planes = [int(plane) for plane in planes.split(',')]
    planes.sort()

    edge = planes[-1]
    x = np.linspace(-edge, edge, 250)
    y = np.linspace(-edge, edge, 250)

    regions = []
    cell_hover = []

    # Normal Display
    for i in x:
        row = []
        text_row = []
        for j in y:

            # TODO: Make what_region function
            if np.sqrt(i ** 2 + j ** 2) < planes[0]:
                row.append(7)  # <- Arbitrary number to adjust color
                text_row.append('Region 1')

            if np.sqrt(i ** 2 + j ** 2) > planes[-1]:
                row.append(5)  # <- Arbitrary number to adjust color
                text_row.append('Region {}'.format(len(planes) + 1))

            for k in range(len(planes) - 1):
                if planes[k] < np.sqrt(i ** 2 + j ** 2) < planes[k + 1]:
                    row.append(k * 3)  # <- Arbitrary number to adjust color
                    text_row.append('Region {}'.format(k + 2))
        regions.append(row)
        cell_hover.append(text_row)

    ######################################################
    # Fill region in OpenMC
    outer_radii = []
    for plane in planes:
        outer_radii.append(openmc.ZCylinder(x0=0, y0=0, R=plane, name='{} Outer Radius'))

    cell_universe = openmc.Universe(name='{} Cell'.format(selected_material))

    # Initialize region
    if click_register is not None:
        region = click_register[0]
        click_x = click_register[1]
        click_y = click_register[2]

        # if region == 1:  # For region 1
        #     cell_filling = openmc.Cell(name='', fill=model.materials[selected_material], region=-outer_radii[0])
        #
        # if region == (len(planes) + 1):  # For outer region
        #     cell_filling = openmc.Cell(name='', fill=model.materials[selected_material], region=+outer_radii[-1])
        #
        # for k in range(len(planes) - 1):
        #     if planes[k] < region < planes[k + 1]:  # For in-between regions
        #         cell_filling = openmc.Cell(name='', fill=model.materials[selected_material], region=+outer_radii[k] & -outer_radii[k + 1])

        cell_fillings = []

        if n_clicks > 0:

            new_hover = []

            # cell_fillings.append(cell_filling)

            # Change graph on Click TODO: Not filling region correctly (MUST FIX)
            # TODO: Figure out why new text wont show up
            if 0 < np.sqrt(click_x ** 2 + click_y ** 2) < planes[0]:
                for row_ in cell_hover:
                    for text in row_:
                        new_hover.append(text.replace('Region 1', '{} Region'.format(materials_list[selected_material])))

            if np.sqrt(click_x ** 2 + click_y ** 2) > planes[-1]:
                for row_ in cell_hover:
                    for text in row_:
                        new_hover.append(text.replace('Region {}'.format(len(planes)+1), '{} Region'.format(materials_list[selected_material])))

            for k in range(len(planes) - 1):
                if planes[k] < np.sqrt(click_x ** 2 + click_y ** 2) < planes[k + 1]:
                    for row_ in cell_hover:
                        for text in row_:
                            new_hover.append(text.replace('Region {}'.format(k+2), '{} Region'.format(materials_list[selected_material])))

            cell_hover = new_hover
            print(cell_hover)
            n_clicks = 0

    # cell_universe.add_cells(cell_fillings)
    cell_universes.append(cell_universe)
    ######################################################

    heatmap = go.Heatmap(z=regions, x=x, y=y, hoverinfo='x+y+text', text=cell_hover, opacity=0.5)

    data = [heatmap]
    shapes = []

    for plane in planes:
        shape = {
            'type': 'circle',
            'x0': -plane,
            'y0': -plane,
            'x1': plane,
            'y1': plane,
            'line': {
                'width': 4,
            },
            'opacity': 1
        }

        shapes.append(shape)

    layout = dict(title='Test',
                  height=1000,
                  width=1000,
                  shapes=shapes)

    figure = dict(data=data, layout=layout)

    return figure
```

I can verify that prior to clicking the `fill-region-button`, the hover text is as expected. Then, after clicking the button, the hover label is still visible but the text is removed. I can also verify that `new_hover` is not an empty list. Is Dash not capable of updating hover text? 

Thanks

**Comment by chriddyp** [comment] 2018-03-22 23:43
Hmm, odd. Not sure what's going on here. Would be helpful to see a very simple reproducable example (e.g. 30 lines of code)

**Comment by SterlingButters** [comment] 2018-03-22 23:48
The most minimal I have until I can get to my computer is here: https://community.plot.ly/t/can-same-component-id-reside-in-input-state-and-output-simultaneously/9125

**Comment by SterlingButters** [comment] 2018-03-22 23:51
And in fact, Idk how much more minimal I can get. I can probably remove the invoke_material_options function and I think that’s about it

**Comment by chriddyp** [comment] 2018-03-23 00:04
@SterlingButters - I recommend starting from scratch when trying to recreate reproducable examples. This is what I usually do when I investigate a bug (see https://github.com/plotly/dash-recipes for a bunch of examples). So, related to the original report:
> Component property 'figure' will not update hover-text for go.Heatmap object

I would expect a simple, reproducable example to look something like:

```
import dash
from dash.dependencies import Input, Output
import dash_core_components as dcc
import dash_html_components as html

app = dash.Dash()

app.layout = html.Div([
    html.Button(id='button'),
    dcc.Graph(id='graph')
])

@app.callback(Output('graph', 'figure'), [Input("button", 'n_clicks')])
def update_graph(n_clicks):
    return {'data': [{'z': [[n_clicks, n_clicks, n_clicks]], 'type': 'heatmap'}]}

if __name__ == '__main__':
    app.run_server(debug=True)
```

Now, I haven't actually run this example and I don't know if that's what you mean in your original report, but that's the type of example that is minimal (not a line of code can be removed or needs to be added) and might demonstrate the issue.

I usually ask for these types of examples not just to make my life easier (although it does! Otherwise, I have to parse through the example provided, make it work on my machine, and then iteratively remove code until I know that nothing else in the example is causing the issue) but because going through this process will more often than not expose an issue in userland rather than in the underlying example.

**Comment by SterlingButters** [comment] 2018-03-23 05:16
I'm pretty sure I figured out the problem but I won't close the issue till I am sure. Looks like a user error though... whoops O.O

**Comment by chriddyp** [comment] 2018-03-27 00:02
Closing this for now, feel free to repoen if you can reduce it to something simple like what was posted above

**Closed by chriddyp** 2018-03-27 00:02 UTC

**Comment by SterlingButters** [comment] 2018-03-28 02:54
Here is a minimal example that is supposed to "highlight" the selected "region". It uses the same principle and it should be easier to debug.

```
import dash
import dash_core_components as dcc
import dash_html_components as html
from dash.dependencies import Output, State, Input

import plotly.graph_objs as go
import numpy as np

app = dash.Dash()
app.config['suppress_callback_exceptions'] = True

#######################################################################################################################

app.layout = html.Div([
    html.Div([
        dcc.Graph(id='graph'),
        dcc.Input(id='planes-list', value=.5, type='number'),
    ])])


@app.callback(
    Output('graph', 'figure'),
    [Input('planes-list', 'value')],
    [State('graph', 'clickData')]
)
def highlight_region(plane, clickData):
    edge = plane
    x = np.linspace(-edge, edge, 250)
    y = np.linspace(-edge, edge, 250)

    regions = []
    cell_hover = []
    for i in x:
        row = []
        text_row = []
        for j in y:

            if np.sqrt(i ** 2 + j ** 2) < plane:
                row.append(4)
                text_row.append('Region 1')

            if np.sqrt(i ** 2 + j ** 2) > plane:
                row.append(9)
                text_row.append('Region 2')

        regions.append(row)
        cell_hover.append(text_row)

    ######################################################
    if clickData is not None:
        if 'points' in clickData:
            point = clickData['points'][0]
            if 'x' in point:
                click_x = point['x']
            if 'y' in point:
                click_y = point['y']

        hilit_regions = []
        if 0 < np.sqrt(click_x ** 2 + click_y ** 2) < plane:
            for row_ in regions:
                for num in row_:
                    hilit_regions.append(5)

        if np.sqrt(click_x ** 2 + click_y ** 2) > plane:
            for row_ in regions:
                for num in row_:
                    hilit_regions.append(10)

        regions = hilit_regions
    ######################################################

    heatmap = go.Heatmap(z=regions, x=x, y=y, hoverinfo='x+y+text', text=cell_hover, opacity=0.5, showscale=False)
    data = [heatmap]
    layout = dict(title='Cell Region Depiction',
                  height=1000,
                  width=1000,
                  )
    figure = dict(data=data, layout=layout)
    return figure


if __name__ == '__main__':
    app.run_server(debug=True)
```
