### ISSUE TITLE
[BUG] react Warning: Received `true` for a non-boolean attribute `persistence`

### ISSUE THREAD

**Issue by eddy-geek** [plotly/dash#1209] opened 2020-04-22 15:28 UTC
**System**

- OS: Ubuntu 18.04
- Browser: latest stable, both chrome 81 & firefox 75
-  fresh venv with just `pip install dash`. Also tested in dash 1.10 and master (1.12pre)
```
dash==1.11.0
dash-core-components==1.9.1
dash-html-components==1.0.3
dash-renderer==1.4.0
dash-table==4.6.2
```

**Describe the bug**

With very simple persisted inputs like `dcc.Input(id="input-1-state", type="text", value="Montreal", persistence=True),`, the following warning appears in the javascript console:

```Warning: Received `true` for a non-boolean attribute `persistence````

<details><summary>full code & stack</summary>

with the following code:

```python
import dash_core_components as dcc
import dash_html_components as html
from dash import Dash
from dash.dependencies import Input, Output, State

app = Dash(__name__)

layout = html.Div(
    [
        dcc.Input(id="input-1-state", type="text", value="Montreal", persistence=True),
        dcc.Input(id="input-2-state", type="text", value="Canada", persistence=True),
        html.Button(id="submit-button", n_clicks=0, children="Submit"),
        html.Div(id="output-state"),
    ]
)
app.layout = layout

@app.callback(
    Output("output-state", "children"),
    [Input("submit-button", "n_clicks")],
    [State("input-1-state", "value"), State("input-2-state", "value")],
)
def update_output(n_clicks, input1, input2):
    return (
        "The Button has been pressed {} times,"
        'Input 1 is "{}",'
        'and Input 2 is "{}"'
    ).format(n_clicks, input1, input2)


app.run_server(debug=True, host='0.0.0.0', port=8051)
```

```javascript
Warning: Received `true` for a non-boolean attribute `persistence`.

If you want to write it to the DOM, pass a string instead: persistence="true" or persistence={value.toString()}.
    in input (created by n)
    in n (created by CheckedComponent)
    in CheckedComponent (created by TreeContainer)
    in UnconnectedComponentErrorBoundary (created by withRadiumContexts(UnconnectedComponentErrorBoundary))
    in withRadiumContexts(UnconnectedComponentErrorBoundary) (created by ConnectFunction)
    in ConnectFunction (created by TreeContainer)
    in TreeContainer (created by ConnectFunction)
    in ConnectFunction (created by TreeContainer)
    in div (created by u)
    in u (created by CheckedComponent)
    in CheckedComponent (created by TreeContainer)
    in UnconnectedComponentErrorBoundary (created by withRadiumContexts(UnconnectedComponentErrorBoundary))
    in withRadiumContexts(UnconnectedComponentErrorBoundary) (created by ConnectFunction)
    in ConnectFunction (created by TreeContainer)
    in TreeContainer (created by ConnectFunction)
    in ConnectFunction (created by UnconnectedContainer)
    in div (created by UnconnectedGlobalErrorContainer)
    in div (created by GlobalErrorOverlay)
    in div (created by GlobalErrorOverlay)
    in GlobalErrorOverlay (created by DebugMenu)
    in div (created by DebugMenu)
    in DebugMenu (created by UnconnectedGlobalErrorContainer)
    in div (created by UnconnectedGlobalErrorContainer)
    in UnconnectedGlobalErrorContainer (created by withRadiumContexts(UnconnectedGlobalErrorContainer))
    in withRadiumContexts(UnconnectedGlobalErrorContainer) (created by ConnectFunction)
    in ConnectFunction (created by UnconnectedContainer)
    in UnconnectedContainer (created by ConnectFunction)
    in ConnectFunction (created by UnconnectedAppContainer)
    in UnconnectedAppContainer (created by ConnectFunction)
    in ConnectFunction (created by AppProvider)
    in Provider (created by AppProvider)
    in AppProvider
```
</summary>
</details>

Functionality does not appear to be affected.

**Expected behavior**

No console warning. If I'm doing something wrong, I'd prefer an error in the python logs &| the UI.

**Screenshots**

![image](https://user-images.githubusercontent.com/2772505/80000311-46384680-84bd-11ea-97e0-16539ed648ce.png)

**Comment by alexcjohnson** [comment] 2020-04-22 16:39
Thanks @eddy-geek - this is not harmful but it is certainly annoying. The root cause is prop forwarding with `omit` https://github.com/plotly/dash-core-components/issues/703. Closing here and I'll reference your use case there.

**Closed by alexcjohnson** 2020-04-22 16:39 UTC
