### ISSUE TITLE
[BUG] Import error with typing_extensions == 4.9.0

### ISSUE THREAD

**Issue by abetatos** [plotly/dash#2711] opened 2023-12-14 10:36 UTC
Thank you so much for helping improve the quality of Dash!

We do our best to catch bugs during the release process, but we rely on your help to find the ones that slip through.

**Describe your context**

python 3.9.7 
Linux 
typing_extensions == 4.9.0

```
dash                 2.14.0
dash-core-components 2.0.0
dash-html-components 2.0.0
dash-table           5.0.0
```

**Describe the bug**

When importing dash an error was returned related to typing_extensions (cannot import name 'NotRequired' from 'typing_extensions').
Falling back to the lower version possible that dash permitted for typing extensions fixed the bug (4.1.1)

**Comment by T4rk1n** [comment] 2023-12-14 14:20
Hi @abetatos 

I cannot reproduce this error after installing typing_extensions 4.9.0 on a new linux venv, `NotRequired` import fine and looking at the [changelog](https://github.com/python/typing_extensions/blob/main/CHANGELOG.md) I don't see a removal/deprecation mention. Can you share the stacktrace?

**Comment by abetatos** [comment] 2023-12-14 14:54
Sorry, it was a temporal environment to which I don't have access anymore.
Tried to reproduce it in my local machine but I couldn't replicate the error.

**Comment by Coding-with-Adam** [comment] 2023-12-14 16:04
Closing the issue for now. Issue will be reopened if the aforementioned error can be reproduced.

**Closed by Coding-with-Adam** 2023-12-14 16:04 UTC
