### ISSUE TITLE
[BUG]Unable to UI select when dcc.Graph is updated with a different number of traces

### ISSUE THREAD

**Issue by ycaokris** [plotly/dash#1097] opened 2020-01-28 03:18 UTC
I'm taking this as a **Plotly.js** error but feel like Dash team may need to explore on it.

-  replace the result of `pip list | grep dash` below
```
dash==1.8.0
plotly==4.5.0
```
-  if frontend related, tell us your Browser, Version and OS

    - OS: MacOS
    - Browser: Chrome Mac (this happens on Firefox as well)
    - Version 79.0.3945.117 

**Describe your context**

I'm writing an app which updates dcc.Graph() with callback, inside this callback a **choroplethmapbox** with additional traces is made. 

What I noticed is that although returning a different number of trace manages to update my map, I can not apply user-interaction on the map like drag-lasso. In the console lasso on the updated graph raises:

```
async~plotlyjs.v1_7_0m1579024535.js:1 Uncaught TypeError: Cannot read property 'updateOnSelect' of undefined
    at styleOnSelect (async~plotlyjs.v1_7_0m1579024535.js:1)
    at E (async~plotlyjs.v1_7_0m1579024535.js:1)
    at async~plotlyjs.v1_7_0m1579024535.js:1
    at l (async~plotlyjs.v1_7_0m1579024535.js:1)
    at Object.r.throttle (async~plotlyjs.v1_7_0m1579024535.js:1)
    at Object.a.moveFn (async~plotlyjs.v1_7_0m1579024535.js:1)
    at HTMLDocument.w (async~plotlyjs.v1_7_0m1579024535.js:1)
```

<img width="697" alt="Screen Shot 2020-01-27 at 10 03 45 PM" src="https://user-images.githubusercontent.com/35306149/73232413-2957d580-4151-11ea-9003-9306bea3f5e6.png">

If I **resize** window my un-responsive lasso turn active again. This lasso-event is fine if graph is updating with the same number of traces.

I've attached a test-script to replicate this issue, press button to update a single trace plot to a double trace plot, and select with drag-lasso tool. 

And gif: 
![app](https://user-images.githubusercontent.com/35306149/73232757-53f65e00-4152-11ea-8f9c-f95b47a22356.gif)

Attached test script: 

```python
import dash
print(dash.__version__)
import dash_core_components as dcc
import dash_html_components as html
from dash.dependencies import Input, Output, State
from dash.exceptions import PreventUpdate
import plotly.graph_objects as go
import plotly.express as px
import json
from urllib.request import urlopen

with urlopen('https://raw.githubusercontent.com/plotly/datasets/master/geojson-counties-fips.json') as response:
    counties = json.load(response)

import pandas as pd

df = pd.read_csv("https://raw.githubusercontent.com/plotly/datasets/master/fips-unemp-16.csv",
                 dtype={"fips": str})

fig = go.Figure(data=[go.Choroplethmapbox(geojson=counties, locations=df.fips, z=df.unemp,
                                    colorscale="Viridis", zmin=0, zmax=12,
                                    marker_opacity=0.5, marker_line_width=0)
                      ])

fig2 = go.Figure(
    data=[
        go.Choroplethmapbox(geojson=counties, locations=df.fips, z=df.unemp,
                            colorscale="Viridis", zmin=0, zmax=12,
                            marker_opacity=0.5, marker_line_width=0),
        go.Scattermapbox(
            mode="markers",
            lon=[-85.416437], lat=[31.619466],
            marker={'size': 30},
            )
    ]
)

fig.update_layout(mapbox_style="carto-positron",
                  mapbox_zoom=3,
                  mapbox_center={"lat": 37.0902, "lon": -95.7129},
                  dragmode='lasso'
                  )

fig2.update_layout(
    mapbox_style="carto-positron",
    mapbox_zoom=3, mapbox_center={"lat": 37.0902, "lon": -95.7129},
    dragmode='lasso'
)

# Graph 1
graph_1 = fig

# Graph 2
graph_2 = fig2

app = dash.Dash(__name__)
server = app.server
app.config.suppress_callback_exceptions = True

app.layout = html.Div(
    [
        html.Button(id='btn', children='Click to update map', n_clicks=0),
        dcc.Graph(id='map', figure=graph_1, config={'responsive': True})
    ]
)


# Callback to update this map
@app.callback(
    Output('map', 'figure'),
    [Input('btn', 'n_clicks')]
)
def update_map(n_click):
    if n_click:
        return graph_2
    if n_click % 2:
        return graph_1
    raise PreventUpdate


if __name__ == "__main__":
    app.run_server(
        debug=True, port=8052
    )

```

**Expected behavior**

I expect select effect shouldn't be affected regardless of what type of graph is updated.

**Comment by Kully** [comment] 2022-10-10 08:43
@ycaokris Unfortunately I am hitting the same bug with a personal project.

Even the latest release to date (5.10.0) still has the same issue :(

<img width="948" alt="image" src="https://user-images.githubusercontent.com/10369095/194828515-5d315b90-cd02-4b9d-af4a-b6e8448a3461.png">

**Comment by alexcjohnson** [comment] 2022-10-20 15:46
Simplified app with updated syntax below. One thing to note: even if you click the button twice, to get back to a single trace, selecting still gives an error.

```py
from dash import Dash, dcc, html, Input, Output
import plotly.graph_objects as go
import json
import pandas as pd
from urllib.request import urlopen

with urlopen('https://raw.githubusercontent.com/plotly/datasets/master/geojson-counties-fips.json') as response:
    counties = json.load(response)

df = pd.read_csv(
    "https://raw.githubusercontent.com/plotly/datasets/master/fips-unemp-16.csv",
    dtype={"fips": str}
)

choropleth = go.Choroplethmapbox(
    geojson=counties, locations=df.fips, z=df.unemp, colorscale="Viridis",
    zmin=0, zmax=12, marker_opacity=0.5, marker_line_width=0
)

fig = go.Figure(data=[choropleth])

fig2 = go.Figure(data=[
    choropleth,
    go.Scattermapbox(
        mode="markers", lon=[-85.416437], lat=[31.619466], marker={'size': 30}
    )
])

layout_updates = dict(
    mapbox_style="carto-positron",
    mapbox_zoom=3,
    mapbox_center={"lat": 37.0902, "lon": -95.7129},
    dragmode='lasso'
)
fig.update_layout(**layout_updates)
fig2.update_layout(**layout_updates)

app = Dash(__name__)
app.layout = html.Div([
    html.Button(id='btn', children='Click to update map', n_clicks=0),
    dcc.Graph(id='map', config={'responsive': True})
])


# Callback to update this map
@app.callback(Output('map', 'figure'), Input('btn', 'n_clicks'))
def update_map(n_click):
    return fig2 if n_click % 2 else fig


if __name__ == "__main__":
    app.run_server(debug=True)
```

**Comment by 5fcgdaeb** [comment] 2023-02-15 15:35
This problem is still there, causing various UX issues for us.

Any progress here? Or any workarounds that anyone can think of?

**Comment by Kully** [comment] 2023-02-15 15:39
> Any progress here? Or any workarounds that anyone can think of?

I think this was already solved. See [this line](https://github.com/plotly/plotly.js/blob/master/CHANGELOG.md#fixed-8) in the CHANGELOG.

@alexcjohnson Does this mean we can close this issue since a more uptodate version of `plotly.js` fixes the bug?

**Comment by alexcjohnson** [comment] 2023-02-15 15:50
@Kully I think you're right about the release that fixed this, and this - and it's been included downstream for a while now, if I use the latest version of Dash (2.8.1) and plotly.py (5.13.0) I don't see this bug anymore with the simple test app [above](https://github.com/plotly/dash/issues/1097#issuecomment-1285782694). Can you confirm that using the latest versions fixes it for you too?

@5fcgdaeb what versions of these packages are you using? If you're still seeing this on the latest, can you give a reproduction app?

**Comment by 5fcgdaeb** [comment] 2023-02-15 16:19
Thanks for the quick turnaround guys, really appreciated.

Getting the details from @ugurzcifci and will post here.

**Comment by Kully** [comment] 2023-02-15 16:23
> Can you confirm that using the latest versions fixes it for you too?

I am quite busy these days so will be better to defer to someone else to verify. (@5fcgdaeb would you be able to check this?)

Thanks for understand.

**Comment by ugurzcifci** [comment] 2023-02-16 16:56
Thanks for prompt replies. I'm looking into this, will let you know if the latest version fixes it or not in short time.

**Comment by ugurzcifci** [comment] 2023-02-17 09:24
It's working after upgrading to Dash 2.8.1 and plotly 5.13.0. I think you can close this issue, thanks for the help!

**Closed** 2023-02-17 14:07 UTC
Labels: dash-type-bug
