### ISSUE TITLE
Error loading dependencies

### ISSUE THREAD

**Issue by micmizer** [plotly/dash#2953] opened 2024-08-20 15:44 UTC
**Describe your context**
Please provide us your environment, so we can easily reproduce the issue.

I can reproduce this very easily unfortunately the app is quite large and I suspect this is due to something specific with the app. I have rolled back many commits and cannot identify when it started.

-  replace the result of `pip list | grep dash` below
```
$ pip freeze | grep dash
dash==2.17.1
dash-bootstrap-components==1.5.0
dash-bootstrap-templates==1.1.2
dash-core-components==2.0.0
dash-extensions==1.0.14
dash-html-components==2.0.0
dash-iconify==0.1.2
dash-table==5.0.0
dash_mantine_components==0.14.4
```

-  if frontend related, tell us your Browser, Version and OS
 -OS: MacOS
-Browser: Chrome
- Version 127.0.6533.120 (Official Build) (arm64)

**Describe the bug**

When running in development mode locally the first start of dash returns "Error loading dependencies". A refresh allows the app to load.

**Expected behavior**

Better debug-ability as it is incredibly difficult to identify what is causing this. The problem disappears after the first hard page refresh. Can provide data if someone can provide direction on how best to determine the cause.

**Screenshots**
Console log
<img width="1708" alt="Screenshot 2024-08-20 at 10 17 13 AM" src="https://github.com/user-attachments/assets/6cc77088-3eb1-4933-850d-2e490a7f36ac">

Page only displaying "Error loading dependencies"
<img width="251" alt="Screenshot 2024-08-20 at 10 37 39 AM" src="https://github.com/user-attachments/assets/635c9439-a693-48f9-af8c-253d0c2a4660">

In further testing in incognito mode i get the following:
<img width="1298" alt="Screenshot 2024-08-20 at 10 49 11 AM" src="https://github.com/user-attachments/assets/aa4d94b0-4776-434d-906d-9cd37d8af77d">

**Comment by AnnMarieW** [comment] 2024-08-20 16:38
Hi @micmizer 

I see on [discord](https://discord.com/channels/932931236882677780/932931237398581310/1275482168277205137) that you said this was fixed when you re-installed the dependencies.  Can this be closed now?

**Comment by AnnMarieW** [comment] 2024-08-21 16:16
Hi @micmizer 

I'm going to close this for now since it seems you have found a solution.  If the problem persists, please feel free to reopen and include a minimal example that reproduces the error.

**Closed by AnnMarieW** 2024-08-21 16:16 UTC
Labels: bug, P3
