### ISSUE TITLE
Blueprint

### ISSUE THREAD

**Issue by stsouko** [plotly/dash#21] opened 2017-06-21 19:49 UTC
Hello!

Is it possible to use Blueprint for instancing Dash app? not flask app itself.

this give easy integration to existing apps.

**Comment by chriddyp** [comment] 2017-06-21 19:54
Good question. I haven't looked into Blueprints recently so I'm not too familiar with how this would work or what it would provide. I'd appreciate some community guidance here.

Are you just looking to use Dash in an existing Flask app? One way to do this right now would be to just run Dash separately from the your other Flask instances and embed the Dash apps as an Iframe in your templates.

**Comment by DavidUnzue** [comment] 2017-06-23 13:15
As far as I understood after reading the user guide, one would need to write a new Dash (Flask) application for each plot instance, since the layout of the page is also bound to the application object. 

It seems there is no support for routing, meaning I can't have different plot instances within the same application, each with it's own layout, listening to a specific route. Something like:

| route                       | rendered plot |
|-----------------------------|---------------|
| myapp.com/plots/barchart    | barchart      |
| myapp.com/plots/scatterplot | scatterplot   |
| ...                         | ...           |

This way, one could even use the contents of the HTTP request, e.g. to specify the data to be plotted.

The concept of [flask blueprints](http://flask.pocoo.org/docs/0.12/blueprints/) might allow to do this, as each blueprint could contain a dash application, and then every blueprint would be registered under a specific route in the main flask application. However, I'm afraid that due to the fact, that every Dash instance creates a full Flask application, blueprints can't be used in this situation. I'm not a blueprint expert though, so I would appreciate if someone with more knowledge could explain this.

@chriddyp please correct me if I misunderstood something here.

**Comment by yunake** [comment] 2017-07-27 01:32
@chriddyp is this correct — there's no way to have more than one chart in the single Flask app right now?

**Comment by shaoeChen** [comment] 2017-09-12 03:48
@chriddyp 
dear..
you means i can use dash like api model?
client user call the api and i return the html to show .

**Comment by nvgoldin** [comment] 2018-03-19 07:35
Would be happy to know if anyone got this working (blueprint or multiple charts in one flask application)

**Comment by vanchung1995** [comment] 2018-11-20 10:38
Hello everyone, I'm wondering that how to get blueprint instance in dash app in init dash plot object? thank you

**Comment by kalimuthu123** [comment] 2021-04-11 13:35
hi i have the same issue in creating how to get blueprint instance in dash app in init dash plot object?

**Comment by gvwilson** [comment] 2024-06-03 13:24
Hi - this issue has been sitting for a while, and we're not planning to tackle it, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson

**Closed by gvwilson** 2024-06-03 13:24 UTC
Labels: Status: Discussion Needed, documentation needed
