### ISSUE TITLE
importing dash causes running of any test.py in same folder as app.py

### ISSUE THREAD

**Issue by np-8** [plotly/dash#1339] opened 2020-07-19 13:30 UTC
I bumped up to a little bit unexpected behaviour: If you import dash, any file called `test.py`  in the same folder will be imported, causing sometimes unexpected behaviour.

## MWE

- Create empty folder with `app.py` and `test.py`

```python
# test.py
print('In test.py')
```

```python
# app.py
print('1 in app.py')
import dash
print('2 in app.py')
```

### Output

```
PS C:\tmp\test_dash> python .\app.py
1 in app.py
In test.py
2 in app.py
``` 

### What would be expected?

One could expect that `import dash` would not run any files called `test.py`. 

### Versions
```
dash                         1.13.4    
dash-core-components         1.10.1
dash-html-components         1.0.3
dash-renderer                1.5.1
```

**Comment by elfjes** [comment] 2020-07-20 09:53
This is an issue with the [future](https://github.com/PythonCharmers/python-future) package that's used for py2/py3 compatibility, not with dash, you may want to pick it up with them. It tries to load a number of modules when importing `future.moves`  defined [here](https://github.com/PythonCharmers/python-future/blob/28b336151e991ddb8d8a4fb48c48f0e2b9784f55/src/future/standard_library/__init__.py#L793):

Question is, with py2 no longer being maintained, does dash still need to use this package, eg [here](https://github.com/plotly/dash/blob/d5452c00ef52c2ddc8059928eacb3a1023e7c872/dash/dash.py#L15)?

**Comment by alexcjohnson** [comment] 2020-07-20 14:34
Duplicate of #1143 
I'm afraid we're not quite ready to drop py2 support yet, but #1143 points to some ways we can at least make things work better, though we probably can't prevent `future` from importing `test` and `org`.

**Closed by alexcjohnson** 2020-07-20 14:34 UTC
