### ISSUE TITLE
[BUG] Fail to draw complex Callback Graph

### ISSUE THREAD

**Issue by doctrino** [plotly/dash#1961] opened 2022-03-09 11:35 UTC
**Context**
```
dash                 2.1.0
dash-core-components 2.0.0
dash-html-components 2.0.0
dash-bootstrap-components 1.0.3
dash-table           5.0.0
```
    - OS: Windows 10
    - Browser chrome
    - Version e.g. 99.0.4844.51

**Describe the bug**

If the callback graph becomes too complex, it seems the underlying `npm `library `dagree` fails to draw it.

**Expected behavior**

The callback graph is drawn for all callbacks, no matter complexity.

**Screenshots**

![image](https://user-images.githubusercontent.com/60234212/157433964-f88adf40-704b-4a66-8d4b-6b5c9a91ea79.png)

![image](https://user-images.githubusercontent.com/60234212/157433677-77bb8219-6205-467b-be31-7b7f25d54312.png)

**Comment by alexcjohnson** [comment] 2022-03-10 02:20
Oh interesting, I know we can handle very _large_ graphs, like the one for the entire docs site, but for all its size that graph isn’t very _complex_ because it’s mainly lots of independent little examples.

Ultimately the fix for this is probably in `dagre`, but it may be possible for us to push the error down enough that after you see the error you can still choose a different layout algorithm, and hopefully another one will work.

**Comment by gvwilson** [comment] 2024-07-23 14:51
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are most important to our community. If this issue is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. (Please note that we will give priority to reports that include a short reproducible example.) If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson

**Closed by gvwilson** 2024-07-23 14:51 UTC
