### ISSUE TITLE
[BUG] Persistence doesn't persist Empty / None / Null values

### ISSUE THREAD

**Issue by notatallshaw** [plotly/dash#1046] opened 2019-12-12 02:50 UTC
**Steps to reproduce**:

1. Use a Dash Core Component with persistence where the value can be emptied
2. Empty the value and refresh the web page

**Actual Results**:

The empty value is not saved and the old value returns

**Expected Results**:

Empty value should still be persistent as it's often a valid UI option

**Example code**:

In this example change value to Montreal and refresh page, then empty the value and refresh the page, you will see the behavior described:

```python
import dash
import dash_html_components as html
import dash_core_components as dcc

app = dash.Dash(__name__)

app.layout = html.Div([
    dcc.Dropdown(
        id='demo-dropdown',
        options=[
            {'label': 'New York City', 'value': 'NYC'},
            {'label': 'Montreal', 'value': 'MTL'},
            {'label': 'San Francisco', 'value': 'SF'}
        ],
        value='NYC',
        persistence=True
    ),
    html.Div(id='dd-output-container'),
])

app.run_server(debug=True)
```

Tested on Python 3.8 with:

    dash                 1.7.0
    dash-core-components 1.6.0
    dash-html-components 1.0.2
    dash-renderer        1.2.2
    dash-table           4.5.1

**Comment by notatallshaw** [comment] 2019-12-12 02:59
This is same as #1034  , would someone be so kind to mark it as a duplicate?

**Comment by alexcjohnson** [comment] 2019-12-12 14:01
Duplicate of #1034 
Thanks @notatallshaw !

**Closed by alexcjohnson** 2019-12-12 14:01 UTC
Labels: Type: Bug

**Comment by alexcjohnson** [comment] 2019-12-12 14:04
huh I thought that would be enough to [mark this one](https://help.github.com/en/github/managing-your-work-on-github/about-duplicate-issues-and-pull-requests)... has that functionality disappeared?
