### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by zedogg** [plotly/dash#2628] opened 2023-08-19 10:36 UTC
I AM FACING AN ISSUE WHILE DEPLOYING AN DASH APP **ON MY IIS SERVER IT IS NOT SHOWING DATA IN GRAPHS AND FEW CARDS** WHIL IT SHOWS DAT IN TABLES ON THE SAME PAGE   AND IT IS WORKING FINE IN MY LOCAL HOST bUT GIVING ME ISSUES ON PRODUCTION SERVER ON WINDOWS IIS SERVER (10.0)

**Comment by AnnMarieW** [comment] 2024-06-03 17:42
I'm going to close this for now since this issue is old and has likely been solved.  Please feel free to re-open and provide some more information including a reproducible example if this is still a problem.

**Closed by AnnMarieW** 2024-06-03 17:42 UTC
