### ISSUE TITLE
Overlap of dropdown menus

### ISSUE THREAD

**Issue by thedimlebowski** [plotly/dash#148] opened 2017-10-26 14:07 UTC
From the tutorial: https://plot.ly/dash/getting-started
Before clicking on the first dropdown:
![image](https://user-images.githubusercontent.com/6419212/32057491-59fb4eae-ba5f-11e7-8557-5737859a433e.png)
After:
![image](https://user-images.githubusercontent.com/6419212/32057522-6c0349d0-ba5f-11e7-932e-9120c44af1bd.png)

**Comment by jkunimune15** [comment] 2018-08-03 15:10
It's not just dropdowns. The graph tools hover box thing does this as well:

<img width="477" alt="captura" src="https://user-images.githubusercontent.com/5607801/43650296-685a5e50-970d-11e8-94c8-87b71756489a.PNG">

~~~~python
import dash
import dash_core_components as dcc
import dash_html_components as html
import plotly.graph_objs as go

app = dash.Dash(__name__)
app.layout = html.Div([
	*[
		html.Div([
			dcc.Dropdown(options=[
				dict(label="Option I", value='0'),
				dict(label="Option II", value='1'),
				dict(label="Option III", value='2'),
			]),
		], style=dict(width='25%', display='inline-block'))
	for i in range(4)],
	dcc.Graph(id='fig', figure=go.Figure()),
])

if __name__ == '__main__':
	app.run_server()


if __name__ == '__main__':
	app.run_server()
~~~~

**Comment by invokermain** [comment] 2018-11-30 16:55
Seeing this issue as well

**Comment by dadamson** [comment] 2019-03-20 17:30
Upping  the z-index of the `Select` element only in the `is-open` state seems to be doing the job for me:
```
.Select.is-open {
    z-index: 1003;
}
```
Here is a fork of @chriddyp 's style-guide with that change: https://codepen.io/dadamson/pen/vPVxxq.css

**Comment by gvwilson** [comment] 2024-06-03 13:28
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson

**Closed by gvwilson** 2024-06-03 13:28 UTC
