### ISSUE TITLE
Dash & XLwings. Attempting to pre-load Excel before Dash callback to save load time.

### ISSUE THREAD

**Issue by karnrage** [plotly/dash#2586] opened 2023-07-06 18:02 UTC
Windows 10 Enterprise for local. Windows Server 2022 Standard for the server

3.10 Python, Microsoft 365 Apps for enterprise, 0.28.7 xlwings

I have a web interface project that is using a connection between XLwings and Dash. The Excel file is large and takes about 15 seconds to load, while the calc only takes 5 seconds. Since it is setup to run over the web, each client will have their own instance of Excel. XLwings has a way to handle this.
15 seconds is local, 23 on the server for some reason.
Currently the setup is that once the user enters their setup and clicks submit, only then does the connection start.
If this was normal python, I could just start the connection earlier. However, with Dash the only connection between the layout, and the function definition is the Dash callback.
The goal is to load the Excel file as soon as the page is loaded, while that is happening the user would enter their parameters, the time that takes to load would be saved and the result return time would be shortened by that time.
*
I would like to use a chained callback. The first callback would load on page load with the xlWings connection. 'prevent_initial_call' would be false.
The final callback I have setup the 'prevent_initial_call' to True because I don't want this to run until they hit submit.
*
If I setup the connection as a variable or function, it doesn't look like you can pass these through the callback in anyway.
Project requirements are that the Excel and its VBA not be converted to Python/Dash.
Possible to launch one, or a few, Excels' on launch, and have XLwings grab the PID somehow? Would another Excel extension handle this? I know we're not supposed to use 'Global' variables, but that might fit this particular need.

**Comment by alexcjohnson** [comment] 2023-07-12 23:17
duplicate of https://github.com/plotly/dash-core-components/issues/1008 (although in the future if you have bug reports or feature requests, this is the active repo, dash-core-components and dash-table have been merged in here)

**Closed by alexcjohnson** 2023-07-12 23:17 UTC
